### ISSUE TITLE
Update engines for node 6.x

### ISSUE THREAD

**Issue by tuckerconnelly** [basicdays/co-pg#10]
Getting an error on install with yarn

**Comment by basicdays** [comment]
Interesting, thanks for letting me know, will look into it.

**Comment by basicdays** [comment]
Just replicated the issue and added node ^6.0.0 to the engines list. Version 2.0.1 should provide the fix.

**Comment by tuckerconnelly** [comment]
@basicdays Can you add Node 7? 🙃

**Comment by basicdays** [comment]
Can do.

**Comment by tuckerconnelly** [comment]
@basicdays gentle reminder :)

**Comment by basicdays** [comment]
Aright, looks like everything is working and published. v2.0.2 should work. I just ended up removing the engines from package.json to prevent yarn from being an issue.
