### ISSUE TITLE
More of a question about running co-pg with express....

### ISSUE THREAD

**Issue by born2net** [basicdays/co-pg#5]
I am wondering if when running pg-co with node express server, do you connect to the database on every client connection? or keep a global connection?

In other words, here is my node module:

module.exports.set = function(app, worker_id) {

    var ms = require("mslibmod"),
        co = require('co'),
        async = require('async'),
        pgconn = require('pgconn').create(),
        pg = require('co-pg')(require('pg')),
        exec = require('co-exec'),
        thunkify = require('thunkify');

    app.get('/getLines', function(req, res, next) {
        var id = req.param('id');

        co(function*() {
            try {
                var pgHandle = yield pg.connect_(pgconn.dbserver('galaxy'));
                var statement = 'select business_name FROM business_info WHERE business_id = ' + '1016';
                var result = yield pgHandle[0].query_(statement);
                pgHandle[1]();  // pg queue done
                if (result.rows[0] == undefined){}
                ms.log(result.rows[0].business_name);

            } catch (e) {
                console.error('Panic: ' + e.toString());
            }
        })();

        res.send({});
    });
}

notice how I run the command:           
var pgHandle = yield pg.connect_(pgconn.dbserver('galaxy'));

everytime a new express client is connected, is this the correct approach?
wouldn't lead to memory leaks?

regards,

Sean.

**Comment by danneu** [comment]
First of all, are you aware of Koa (https://github.com/koajs/koa, http://koajs.com/)? Koa is pretty much made for `co`.

Your current code has a lot of issues. I honestly think you should either us Express+node-pg or Koa+co-pg+co.

To answer your question, the intended use for the connection pool is for you to take a connection from the pool, issue a queries across it, and then either release it when all goes well or remove it from the pool upon failure.

`done()` releases the connection. `done(<truthy>)` removes it. So you should wrap your query in a try/catch so that you `catch(ex) { done(ex); ... }`. Else you're returning a botched connection back to the pool.

Your current code leaks a connection upon failure among other issues. And I don't even have a good enough grasp of co to understand all the gotchas with what you're trying to do in general.

**Comment by born2net** [comment]
First thanks for replying, and yes I am aware of the leak in case of an error.
I fixed it a while back, here is my latest code.
Can you please review it and give me your opinion.

As for Koa, I will check it out... Thanks again for the time and here is my latest coding pattern:


   /**
     Fetch Model line table
     @method getLine
     @param {Object} req
     @param {Object} res
     **/
    app.get('/Line/:id', function (req, res) {
        var dbFasterQ;
        var id = req.param('id');
        var business_id = req.param('business_id');
        ms.co(function* getLine() {
            try {
                dbFasterQ = yield ms.pgco.connect_(ms.pgconn.dbserver('fasterq'));
                var statement = 'SELECT *sd FROM lines WHERE business_id = ' + business_id + ' AND line_id = ' + id;
                var result = yield dbFasterQ[0].query_(statement);
                dbFasterQ[1]();  // pg queue done
                if (result.rows[0] == undefined) {
                    res.send({});
                    return;
                }
                res.send(result.rows[0]);

            } catch (e) {
                console.error('Panic getLine: ' + e.toString());
                console.log(dbFasterQ);
                dbFasterQ[1]();  // pg queue done
            }
        })();

**Comment by born2net** [comment]
<pre>
   /**
     Fetch Model line table
     @method getLine
     @param {Object} req
     @param {Object} res
     **/
    app.get('/Line/:id', function (req, res) {
        var dbFasterQ;
        var id = req.param('id');
        var business_id = req.param('business_id');
        ms.co(function* getLine() {
            try {
                dbFasterQ = yield ms.pgco.connect_(ms.pgconn.dbserver('fasterq'));
                var statement = 'SELECT *sd FROM lines WHERE business_id = ' + business_id + ' AND line_id = ' + id;
                var result = yield dbFasterQ[0].query_(statement);
                dbFasterQ[1]();  // pg queue done
                if (result.rows[0] == undefined) {
                    res.send({});
                    return;
                }
                res.send(result.rows[0]);

            } catch (e) {
                console.error('Panic getLine: ' + e.toString());
                console.log(dbFasterQ);
                dbFasterQ[1]();  // pg queue done
            }
        })();

</pre>

**Comment by basicdays** [comment]
Just going through old issues. Don't know if you ever followed through on this. My recommendation would be to use the pooling connections on anything beyond a simple node script. However the usage/patterns beyond being able to yield/await the promises are the exact same as the original driver. I would check in there with any questions regarding general usage.

https://github.com/brianc/node-postgres
