### ISSUE TITLE
Provide better and more helpful examples

### ISSUE THREAD

**Issue by danneu** [basicdays/co-pg#6]
The examples, especially when visible on the README, should at the very least be robust enough for people to copy and paste into their codebase. For example, both examples so far leak a connection upon error.

Furthermore, the examples might as well show how you would actually use the library in your projects. You would generally implement two abstractions in your `db.js` file: a `query` function that just runs one query, and a `withTransaction` function that wraps queries in a BEGIN/COMMIT/ROLLBACK.

**Update**: Here are new versions of the wrapper code I snipped out below: https://github.com/danneu/koa-skeleton/blob/4d654c8963848d171e9b2ae3e0ef91721058d1e1/src/db/util.js

----

    <snipped out old code>

These would be much more helpful to people. What do you think?

The idea is that people should be able to copy `query` and `withTransaction` into their `db.js` and immediately get to work.

**Comment by ranadeep47** [comment]
Thanks, really helpful.

**Comment by born2net** [comment]
tx for that......!

**Comment by dschinkel** [comment]
I agree, what you aren't showing is the caller for this.  so co() returns a promise right?  what would you do  with that, you don't show any example with what you do with the co().

**Comment by BabakMN** [comment]
thanks @danneu. Shouldn't there be a `throw ex;` after `done(ex);` to re-throw caught exceptions?

**Comment by danneu** [comment]
@BabakMN: You're right, I wrote that code from the hip for this issue and its misleading.

Here's an updated version of my wrappers: https://github.com/danneu/koa-skeleton/blob/4d654c8963848d171e9b2ae3e0ef91721058d1e1/src/db/util.js

I'll update the OP.

**Comment by basicdays** [comment]
Going through and cleaning up old issues. Other than the addition of methods that return promises, everything else about this package is the exact same as the original driver. As far as the examples, it's more or less a copy of the original project's examples only using `co`. For usage questions, I would check out the original project's documentation.

https://github.com/brianc/node-postgres
