### ISSUE TITLE
Troubleshooting Connections

### ISSUE THREAD

**Issue by dschinkel** [basicdays/co-pg#7]
I have the following line.  It fires off and I never hear anything back.  It never calls back and nothing is caught in the try-catch so how else can I tell what happened if it never fails and never calls back?

var connectionResults = yield pg.connectPromise(config.connection); // this never calls back after trying to connect

**Comment by basicdays** [comment]
Could you show me your entire function? Are you able to create a gist that reproduces the issue? My initial guess is that it's not within a co-routine.

**Comment by basicdays** [comment]
Closing due to lack of examples.
