### ISSUE TITLE
Is this Co wrapper still being maintained?

### ISSUE THREAD

**Issue by nitetrik** [basicdays/co-pg#8]
Was wondering if this Co-Wrapper is still being maintained?

**Comment by basicdays** [comment]
Yes it is actually. Feel free to let me know if you run into issues anywhere.

**Comment by basicdays** [comment]
Tell you what, I'll probably go through it this weekend and update tests to run against a current PG driver version to ensure it's still working. I'll mark this issue closed when that's finished.

**Comment by nitetrik** [comment]
@basicdays That would be great, cheers.

**Comment by basicdays** [comment]
Hey @nitetrik, sorry about the late feedback. Good news is everything was working to start with. I went ahead and overhauled how I was testing by adding Vagrant to allow future testing to be much easier. New version is now v2.0.0.
