### ISSUE TITLE
how to config user and password in `connectionString`

### ISSUE THREAD

**Issue by jasonliao** [basicdays/co-pg#9]
Hi, I got problem when I connect my local postgreSQL on windows 7. 

Here's the code(actually your demo)

```javascript
var co = require('co');
var pg = require('co-pg')(require('pg'));

var connectionString = 'postgres://postgres:5432@localhost/mmocad_result';  // custom config

co(function *() {
    try {
        var client = new pg.Client(connectionString);
        yield client.connectPromise();

        var result = yield client.queryPromise('select * from public.usertable');
        console.log(result.rows[0].theTime);

        client.end();
    } catch (ex) {
        console.error(ex); 
    }
});
```

catch `error: password authentication failed for user "postgres"`. I think is something wrong with my `connectionString`, but I hava no idea how to config my user or password.

postgresSQL version 9.6
user postgres
password root

Thanks! =]

**Comment by jasonliao** [comment]
Sorry for disturbing... 

`postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]`

**Comment by basicdays** [comment]
Hey @jasonliao, thanks for updating. Good to hear you got it working. In the future, most of the documentation of node-postgres can be found here: https://github.com/brianc/node-postgres

I'll have to go in and update my examples and also provide better documentation on how to get additional help.
